<a href="https://colab.research.google.com/github/Chandini-M555/Data_Science_Task/blob/main/numpy_task.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#creating and reshaping
#creating arrays
import numpy as np
arr1=np.random.randint(0,20,10)
arr2=np.random.randint(5,20,9)
arr2=arr2.reshape(3,3)
print(arr1)
print(arr2)

[ 5 14  8  6  5 10 11  6  4  6]
[[15 18  8]
 [18 15 14]
 [10 13 13]]


In [ ]:
#array dimensions
arr1.ndim


1

In [ ]:
arr2.ndim

2

In [ ]:
#reshaping 1-d to 2-d
arr1.reshape(2,5)

array([[ 5, 14,  8,  6,  5],
       [10, 11,  6,  4,  6]])

In [ ]:
#reshaping 2-d again to 1-d
arr1.reshape(-1)

array([ 5, 14,  8,  6,  5, 10, 11,  6,  4,  6])

In [ ]:
#indexing
print(arr2[1,2]) -->element at 2nd row and third column

np.int64(14)

In [ ]:
#slicing
print(arr2[0:2,1:3])
print(arr1[0:4])
arr1[::-1]

[[18  8]
 [15 14]]
[ 5 14  8  6]


array([ 6,  4,  6, 11, 10,  5,  6,  8, 14,  5])

In [ ]:
#array arithmetic
arr3=np.arange(1,11)
print(arr3)
print(arr1+arr3)
print(arr1*arr3)
print(arr3-5)


[ 1  2  3  4  5  6  7  8  9 10]
[ 6 16 11 10 10 16 18 14 13 16]
[ 5 28 24 24 25 60 77 48 36 60]
[-4 -3 -2 -1  0  1  2  3  4  5]


In [ ]:
#random  numbers
arr4=np.random.rand(5)
arr5=np.random.randn(5)
print(arr4)
print(arr5)


[0.13574801 0.48786707 0.87464728 0.87654614 0.8072515 ]
[ 0.77843406 -2.06858188 -0.45242542  2.75392319 -1.00698879]


In [ ]:
#challenging task
# wap that asks the user to input a number n and then generate  an n by n array of
#  random integers btwn 1 and 100
n=int(input("enter:"))
arr1=np.random.randint(1,100,n*n)
print(arr1)
#find sum of all elements in the array and print result
print(np.sum(arr1))


enter:3
[75 64 26 58 59 73 36 45 14]
450
